apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xnat-web.fullname" . }}
  labels:
    {{- include "xnat-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  xnat-conf.properties: |
    #
    # xnat-conf.properties
    # XNAT http://www.xnat.org
    # Copyright (c) 2016, Washington University School of Medicine
    # All Rights Reserved
    #
    # Released under the Simplified BSD.
    #
    datasource.driver=org.postgresql.Driver
    datasource.url=jdbc:postgresql://{{ template "xnat-web.postgresql.fullname" . }}/{{ .Values.postgresql.postgresqlDatabase }}
    datasource.username={{ .Values.postgresql.postgresqlUsername }}
    datasource.password={{ .Values.postgresql.postgresqlPassword }}
    hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.hbm2ddl.auto=update
    hibernate.show_sql=false
    hibernate.cache.use_second_level_cache=true
    hibernate.cache.use_query_cache=true
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xnat-web.fullname" . }}-auth
  labels:
    {{- include "xnat-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $method, $element := .Values.authentication.methods }}
  {{- if eq $method "openid" }}
  openid-provider.properties: |
    name={{ $element.name }}
    provider.id=openid
    auth.method=openid
    # OpenID method specific configuration
    type=openid
    enabled={{ range $i, $e := $element.providers }}{{ if $i }},{{ end }}{{ $e.id }}{{ end }}
    visible=true
    auto.enabled=true
    auto.verified=true
    disableUsernamePasswordLogin={{ $element.disableUsernamePasswordLogin }}
    siteUrl=PPP
    preEstablishedRedirUri=/openid-login
    {{- range $element.providers }}
    {{ $method }}.{{ .id }}.clientID={{ .clientID }}
    {{ $method }}.{{ .id }}.clientSecret={{ .clientSecret }}
    {{ $method }}.{{ .id }}.accessTokenUri={{ .accessTokenUri }}
    {{ $method }}.{{ .id }}.userAuthUri={{ .userAuthUri }}
    {{ $method }}.{{ .id }}.scopes={{ range $i, $e := .scopes }}{{ if $i }},{{ end }}{{ $e }}{{ end }}
    {{ $method }}.{{ .id }}.link={{ if eq .id "aaf" -}}
      <p>To sign-in using your AAF credentials, please click on the button below.</p><p><a href="/openid-login?providerId=aaf"><img src="/images/aaf_service_223x54.png" /></a></p>
    {{- else if eq .id "google" -}}
      <p>To sign-in using your Google credentials, please click on the button below.</p></p><p><a href="/openid-login?providerId=google"> <img src="/images/btn_google_signin_dark_normal_web.png" /> </a></p>
    {{- end }}
    {{ $method }}.{{ .id }}.shouldFilterEmailDomains={{ .shouldFilterEmailDomains }}
    {{ $method }}.{{ .id }}.allowedEmailDomains={{ range $i, $e := .allowedEmailDomains }}{{ if $i }},{{ end }}{{ $e }}{{ end }}
    {{ $method }}.{{ .id }}.forceUserCreate={{ .forceUserCreate }}
    {{ $method }}.{{ .id }}.userAutoEnabled={{ .userAutoEnabled }}
    {{ $method }}.{{ .id }}.userAutoVerified={{ .userAutoVerified }}
    {{- $id := .id -}}
    {{- range $property, $attribute := .propertyNames }}
    {{ $method }}.{{ $id }}.{{ $property }}Property={{ $attribute }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if eq $method "ldap" }}
  {{- range .providers }}
  {{ .id }}-provider.properties: |
    name={{ .name }}
    provider.id={{ .id }}
    auth.method={{ $method }}
    address={{ .address }}
    userdn={{ .userdn }}
    password={{ .password }}
    search.base={{ .search.base }}
    search.filter={{ .search.filter }}
  {{- end }}
  {{- end }}
  {{- end }}
