---
# development.yaml
# Run using `ansible-playbook -clocal localhost development.yaml`
- hosts: all
  become: yes
  roles:
    - systemd
  vars:
    systemd_multicastDNS: true
- hosts: microk8s
  roles:
    - k8s-dev
    - k8s-cert-manager
- hosts: swarm
  become: yes
  roles:
    - docker
