apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctp.fullname" . }}
  labels:
    {{- include "ctp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1080
      protocol: TCP
      name: http
  selector:
    {{- include "ctp.selectorLabels" . | nindent 4 }}
